server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
  instance:
    hostname: drone-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.musala.services.drone

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dronedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# property for drone ms
drone:
  batteryThreshold: 25.0
  batteryCheckInterval: 360000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans