server:
  port: 8060
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: drone-service
          uri: lb://drone-service
          predicates:
            - Path=/drone/**
          filters:
            - RewritePath=/drone/(?<path>.*), /$\{path}
        - id: medication-service
          uri: lb://medication-service
          predicates:
            - Path=/medication/**
          filters:
            - RewritePath=/medication/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: drone
        url: /v3/api-docs/drone
      - name: medication
        url: /v3/api-docs/medication

management:
  tracing:
    sampling:
      probability: 1.0