spring:
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dronedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# property for drone ms
drone:
  batteryThreshold: 25.0
  batteryCheckInterval: 360000